### ISSUE TITLE
Social account error html - 3rdparty

### ISSUE THREAD

**Issue by josueygp** [danihodovic/django-allauth-ui#100]
when entering the url 'accounts/3rdparty/', I get this error 

![image](https://github.com/user-attachments/assets/06c599fa-0d63-4334-8797-9016b553dee6)

 any solution?

**Comment by danihodovic** [comment]
Fixed in 1.2.1

**Comment by josueygp** [comment]
sorry for the comment, I'm kind of new to github. Have you fixed the bug or are you still going to fix it?

**Comment by danihodovic** [comment]
It's been fixed

**Comment by josueygp** [comment]
Oh, it's fixed now, thank you very much for your hard work.

**Comment by danihodovic** [comment]
Thanks for finding the bug
