### ISSUE TITLE
Question: Customising templates

### ISSUE THREAD

**Issue by svalvaro** [danihodovic/django-allauth-ui#127]
Hi! I'm new to Django, and I have been following this tutorial **(timestamp: 4hrs 25 mins)** https://www.youtube.com/watch?v=WbNNESIxJnY, the author is able to change the `base.html` to have login/signup forms with his own navbar etc. I think this is because he's using an older version of this library. However, I don't know how to dot it in the newer versions and I can't find any examples.

**Comment by danihodovic** [comment]
https://github.com/danihodovic/django-allauth-ui/issues/93

**Comment by svalvaro** [comment]
Thanks, it wasn't really clear to me still (as a beginner). So I just used an older version of the package.

**Comment by GringoDotDev** [comment]
Hi @svalvaro, did you manage to figure something out? I was hoping to override some of the field classes in one of my projects. Thank you!

**Comment by sa-qib** [comment]
> Hi! I'm new to Django, and I have been following this tutorial **(timestamp: 4hrs 25 mins)** https://www.youtube.com/watch?v=WbNNESIxJnY, the author is able to change the `base.html` to have login/signup forms with his own navbar etc. I think this is because he's using an older version of this library. However, I don't know how to dot it in the newer versions and I can't find any examples.

Hey @svalvaro , I am watching the same tutorial and stuck at same problem, any idea how you solved this issue and you can help me
