### ISSUE TITLE
Dead code in allauth_ui.py

### ISSUE THREAD

**Issue by fdobrovolny** [danihodovic/django-allauth-ui#13]
I think this is not used anywhere :thinking: 

https://github.com/danihodovic/django-allauth-ui/blob/3fb6a49828e567c466f2ef1ceed3d6dc2a8a3423/allauth_ui/templatetags/allauth_ui.py#L9-L13

**Comment by danihodovic** [comment]
https://github.com/danihodovic/django-allauth-ui/pull/14
