### ISSUE TITLE
python 3.6

### ISSUE THREAD

**Issue by Heiner92** [danihodovic/django-allauth-ui#19]
Any chance this will work with python 3.6 as well? I can not install it because on pipy python 3.8 or higher is required and I am currently running 3.6 for my django-project...

**Comment by danihodovic** [comment]
Considering the code is mostly HTTP I'm sure we can support 3.6 as well. I think I'll have to make modifications to pyproject.toml and republish the package.

https://github.com/danihodovic/django-allauth-ui/blob/master/pyproject.toml#L13

**Comment by Heiner92** [comment]
Thx! I tested it by manually copying from py3.9 to my py3.6 and there are no issues. Would be nice if you could change dependencies in the pyproject.toml :)

**Comment by danihodovic** [comment]
Should be fixed in 0.0.23

![image](https://user-images.githubusercontent.com/5557301/177372619-6e6ad49b-3216-49a0-8860-5835654cd3c9.png)

**Comment by Heiner92** [comment]
![grafik](https://user-images.githubusercontent.com/32865504/177373524-d1dddbf5-8684-42f0-b95e-1fbc8970e1d9.png)

Unfortunately newer versions of django-widget-tweaks cant be installed as well...
Latest version for py3.6 is 1.4.11

![grafik](https://user-images.githubusercontent.com/32865504/177373767-ef02f555-1c5a-4d12-8e65-8178696983f0.png)

Would be nice if you could change this requirement as well

**Comment by danihodovic** [comment]
Setting it to 1.4.11 creates poetry dependency hell. I think the lowest we can go is 3.6.2 as a bunch of dev dependencies require at least 3.6.2.

**Comment by Heiner92** [comment]
hmmm okay I guess then there is nothing else left for me than upgrading python or manually copying it into site-packages...
Thank you nonetheless for trying 👍

**Comment by danihodovic** [comment]
EOL for 3.6 was 6 months ago, so it's a good idea to upgrade.
