### ISSUE TITLE
Signup screen with social connectors

### ISSUE THREAD

**Issue by aehlke** [danihodovic/django-allauth-ui#23]
It's most typical for websites to show new users a signup screen, which offers username or social signup options. However allauth (and this repo of templates) prefers to show either a username-based signup without social signup options, or a username login form with social options for signup or sign-in. I suggest adding a template/view for the most common pattern, a screen with a signup form (or link to signup form is also fine), and social signin options.

**Comment by danihodovic** [comment]
Can you show me a design of how you would like it to look?

**Comment by aehlke** [comment]
I implemented it here: https://manabi.io/accounts/signup/
