### ISSUE TITLE
password_change.html is missing

### ISSUE THREAD

**Issue by panos23kar** [danihodovic/django-allauth-ui#33]
Hi Dani Hodovic,
congratulations for you great job!
Not sure if it is part of the roadmap but I noticed that the `password_change.html`, `email.html` are missing!

[link](https://github.com/pennersr/django-allauth/blob/77368a84903d32283f07a260819893ec15df78fb/allauth/templates/account/password_change.html)

**Comment by danihodovic** [comment]
Fixed
