### ISSUE TITLE
base_color for buttons

### ISSUE THREAD

**Issue by brettbeeson** [danihodovic/django-allauth-ui#34]
Hi! Thanks for your work!

I just installed and it looks great except the buttons are invisible! For example  [/accounts/password/reset/](url) 
![image](https://github.com/danihodovic/django-allauth-ui/assets/6414228/8bc9ae32-f6b2-4e9e-b7c0-d33c37ed5b95)

To debug I checked the html : `base_color` template variable was missing. I hacked in a context_processor and set `{"base_color": "black"}` 

Then I see the html is (note "black-600"):
`<button type="submit" class="flex items-center justify-center w-64 h-12 px-6 mt-8 text-lg text-white uppercase black-600 rounded text-bold hover:black-700">`

But that still appears invisible. I removed all other css to confirm it's not a conflict. I'm unfamiliar with tailwind but happy to have a crack at recompiling. 

Questions: How do I set base_color properly? How do I make the buttons appear by default?

**Comment by danihodovic** [comment]
Perhaps you have to recompile the tailwind setup. Tailwind strips out css classes that are not in use. See: https://github.com/danihodovic/django-allauth-ui#hacking-on-the-project

Try
```sh
npm run-script build
```

or
```sh
npm run-script build:watch
```

**Comment by danihodovic** [comment]
That's strange, my local installation of allauth works fine

![image](https://github.com/danihodovic/django-allauth-ui/assets/5557301/838e19e4-554d-4934-acf1-39533fe4afcb)

**Comment by danihodovic** [comment]
I recommend you try out https://github.com/cookiecutter/cookiecutter-django

**Comment by brettbeeson** [comment]
Cookiecutter is awesome. Good to learn from the base, but definitely using that for new project. Cheers.
