### ISSUE TITLE
Why is the "remember" field excluded from login.html?

### ISSUE THREAD

**Issue by Hyperz** [danihodovic/django-allauth-ui#39]
I'm referring to [this](https://github.com/danihodovic/django-allauth-ui/blob/2421c3b178c29f9134f3cd832f562c9268be4ef7/allauth_ui/templates/account/login.html#L18). Is there a reason the "Remember me" checkbox is being excluded from the form entirely?

**Comment by danihodovic** [comment]
I can't remember why I made that decision. We should add it. Do you want to open a PR?

Instructions here: https://github.com/danihodovic/django-allauth-ui#hacking-on-the-project

**Comment by Hyperz** [comment]
Looking at what happens when the conditional is removed maybe it was put there to not give the checkbox the same look/styling as the email/password fields, so maybe it was supposed to be an if-else instead of just an if conditional?

As for a PR, I'd love to but I'm still learning Django and Tailwind so I can't right now unfortunately.

**Comment by danihodovic** [comment]
I will see if I can open a PR. Good catch
