### ISSUE TITLE
Make django-allauth-ui work in regular account only config

### ISSUE THREAD

**Issue by fkromer** [danihodovic/django-allauth-ui#44]
https://github.com/danihodovic/django-allauth-ui/blob/697a7d09f13a511557e2b55ee18b6bb34886c250/allauth_ui/templates/account/login.html#L4 leads to a `TemplateSyntaxError at /accounts/login/` during template rendering if `django-allauth` is configured without support for social accounts (regular account only).

**Comment by danihodovic** [comment]
Argh...wanna give it a try and open a pull-request mr fkromer?

**Comment by danihodovic** [comment]
I'll fix this once I make a sweeping change to the design of the UI.

**Comment by danihodovic** [comment]
Released as 0.3.1 https://pypi.org/project/django-allauth-ui/0.3.1/
