### ISSUE TITLE
logout.html button text

### ISSUE THREAD

**Issue by bcomisky** [danihodovic/django-allauth-ui#53]
Seeing this:

![image](https://github.com/danihodovic/django-allauth-ui/assets/30668331/9475a3c7-d4d3-48b2-bff8-bc309ba08b35)

But seems to work as expected if I replace:

```
        {% translate "Sign out" as signout_message }
        {% include "account/_button.html" with text=signout_message %}
```

with

`        {% include "account/_button.html" with text=_("Sign out") %}`

in templates/account/logout.html

Some kind of scoping issue with `signout_message`? I'm very new to Django, so very possibly could be some error on my end.

**Comment by danihodovic** [comment]
Damn

**Comment by danihodovic** [comment]
Thank you @tjmoon0104
