### ISSUE TITLE
Invalid block tag on line 7: '#container'

### ISSUE THREAD

**Issue by nicokant** [danihodovic/django-allauth-ui#76]
`Invalid block tag on line 7: '#container', expected 'endblock'. Did you forget to register or load this tag?`

This error was introduced with `slippers`, self closing tags in slippers don't need starting `#`.

Probably would be useful to have test for these templates, to make sure you are not shipping a broken version.

![Screenshot from 2024-06-25 13-48-17](https://github.com/danihodovic/django-allauth-ui/assets/6927678/b72fa7d1-0e63-4c27-8091-2e18cb5e61be)

**Comment by danihodovic** [comment]
This works perfectly fine for me. Try https://django-allauth-ui.hodovi.ch/accounts/login

**Comment by danihodovic** [comment]
Did you install slippers as a dependency and add it to installed apps? See the Readme

**Comment by nicokant** [comment]
Yes, I already had slippers installed, I also have enabled slippers as builtin template filter (optional part of the installation section of slippers)

**Comment by danihodovic** [comment]
I'm unsure where the problem may be. There are two ways I test this:

- by running the project locally ./manage.py runserver_plus (which uses [test settings](https://github.com/danihodovic/django-allauth-ui/blob/master/tests/settings.py)
- by deploying a [sample app](https://github.com/danihodovic/django-allauth-ui/tree/master/sample_deployment) to Hetzner

1.0.0 was a breaking change so I'll try to help you get upgraded, but I need more info to debug with

**Comment by nicokant** [comment]
I think the problem is that you are using `components.yaml` to describe the library components, but since it's inside `templates` it's going to be replaced by mine `components.yaml` (this is django default override behaviour for templates).
You need to place your components in a separate registry (https://mitchel.me/slippers/docs/registering-components/#adding-components-to-a-different-register) so that it doesn't clash with the components defined by your users.
The "simple" tutorial for slippers is mostly for django projects, not for django reusable apps like in this case :)

**Comment by danihodovic** [comment]
Should be fixed in 1.1.6

**Comment by danihodovic** [comment]
Dies that solve your problem Nico?

**Comment by nicokant** [comment]
I confirm, it's working :)
