### ISSUE TITLE
from a beginner:how can i add my own html content？

### ISSUE THREAD

**Issue by riyuejuyjyj** [danihodovic/django-allauth-ui#91]
Sorry to ask that question seems to be foolished , I noticed that the old version's html pages **(templates/account/)** mostly extend the base html. In the old versions if i want to add a navbar, just add a newfolder named account  under my own templates folder and paste the old version's base html in the account folder,then  put my own content in the base html .But in the new versions the base html has gone,so where could i change ?

  

![chrome_gwHaJDkxUs](https://github.com/danihodovic/django-allauth-ui/assets/105252574/33fd6c94-c17f-4a99-9f01-fec91eec7ce0)
![chrome_QEOwu0WIgg](https://github.com/danihodovic/django-allauth-ui/assets/105252574/d44443e6-9567-4154-b4ef-f51898877a76)

**Comment by danihodovic** [comment]
Place your app above allauth_ui and extend allauth/layouts/base.html in the body block.

https://github.com/danihodovic/django-allauth-ui/blob/master/allauth_ui/templates/allauth/layouts/base.html#L19-L26

For an example see https://github.com/danihodovic/django-allauth-ui/blob/master/sample_deployment/sample_deployment/templates/allauth/layouts/base.html which adds a fixed theme select switcher at https://django-allauth-ui.hodovi.ch/accounts/login/

**Comment by riyuejuyjyj** [comment]
thanks a lot

**Comment by danihodovic** [comment]
You're welcome
